name: Build and Deploy

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Extract version from neutralino.config.json
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<="version": ")[^"]*' neutralino.config.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Install dependencies and build UI
        run: |
          cd client
          npm ci
          npm run build
          cd ..
          npm i -g @neutralinojs/neu@11.3.1
          neu build

      - name: Copy resources.neu to version folder
        run: |
          cp ./dist/ikusa-logger/resources.neu ./version/resources.neu

      - name: Update version-manifest.json
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          sed -i 's/"version": ".*"/"version": "'"$VERSION"'"/' ./version/version-manifest.json
          echo "Updated version-manifest.json to version $VERSION"

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./version/resources.neu ./version/version-manifest.json
          git diff --staged --quiet || git commit -m "deployed new version ${{ steps.get_version.outputs.VERSION }}"
          git push
